# Generated by Django 3.2.5 on 2021-09-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ergo', '0002_auto_20210923_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=36),
        ),
    ]
