# Generated by Django 3.2.5 on 2021-09-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ergo', '0003_alter_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=124),
        ),
    ]
