# Generated by Django 3.2.5 on 2021-09-24 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ergo', '0005_alter_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=124, validators=[django.core.validators.RegexValidator(code='invalid_address', message='Not a valid address', regex='[^\\s-]')]),
        ),
    ]
