# Generated by Django 3.2.5 on 2021-09-24 04:45

from django.db import migrations, models
import ergo.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ergo', '0007_alter_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=124, validators=[ergo.validators.validate_address]),
        ),
    ]
